<template>
  <div class="myteam-skillset fade-in-fwd" :class="`${theme}-skillbar`">
    <div
      class="myteam-skillset-skill"
      :class="`${theme}-skill`"
      v-for="(skill, key) in skills.slice(0,4)"
      :key="key"
      @click="emitSelectedSkill(skill, key)"
    >
      <p v-if="skill.cooldown > 0" class="myteam-skillset-cd">
        {{ skill.cooldown }}
      </p>
      <img
        v-if="inFocus === skill"
        class="pulsate myteam-skillset-skill-icon"
        :src="`/uploads/${skill.skillpic}.jpg`"
      />
      <img
        class="myteam-skillset-skill-icon"
        :class="[
          { fade: skill.disabled || !targetable(skill) },
          { 'fade-fwd': !myData.isTurn },
        ]"
        :src="`/uploads/${skill.skillpic}.jpg`"
      />
    </div>
  </div>
</template>

<style lang="scss">
.fade-out-left {
  -webkit-animation: fade-out-left 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94)
    both;
  animation: fade-out-left 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

@-webkit-keyframes fade-out-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(-50px);
    transform: translateX(-50px);
    opacity: 0;
  }
}
@keyframes fade-out-left {
  0% {
    -webkit-transform: translateX(0);
    transform: translateX(0);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateX(-50px);
    transform: translateX(-50px);
    opacity: 0;
  }
}

.fade-fwd {
  -webkit-animation: fade-fwd 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  animation: fade-fwd 0.7s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
}

/* ----------------------------------------------
 * Generated by Animista on 2020-11-29 13:43:50
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation fade-out-fwd
 * ----------------------------------------
 */
@-webkit-keyframes fade-fwd {
  0% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
  }
  100% {
    -webkit-transform: translateZ(80px);
    transform: translateZ(80px);
    opacity: 0.3;
  }
}
@keyframes fade-fwd {
  0% {
    -webkit-transform: translateZ(0);
    transform: translateZ(0);
  }
  100% {
    -webkit-transform: translateZ(80px);
    transform: translateZ(80px);
    opacity: 0.3;
  }
}
</style>

<script>
export default {
  props: ["skills", "charIndex"],
  methods: {
    emitSelectedSkill(skill, skillIndex) {
      // this emit is received by Viewer/index.vue
      this.$eventBus.$emit("selected-a-skill", skill);

      if (!this.myData.isTurn) return;
      if (this.$store.getters["game/isBusy"]) return;
      // tell server to validate this skill if it hasn't been disabled
      if (!skill.disabled && skill.targetChoices.choice) {
        this.$store.commit("game/setSkillInFocus", skill);
        this.$store.commit("game/setTargetables", skill.targetChoices.choice);
        // received by parent element
        this.$emit("selected-skill", {
          skill: skillIndex,
          caster: this.charIndex,
        });
      }
    },
    validTarget(skill) {
      if (skill.targetChoices) {
        if (skill.targetChoices.choice) {
          if (skill.targetChoices.choice.length) return true;
        }
      }
      return false;
    },
  },
  computed: {
    inFocus() {
      return this.$store.state.game.skillInFocus;
    },
    myData: function () {
      return this.$store.getters["game/GetMyData"](this.myId);
    },
    myId: function () {
      return this.$store.getters["user/getUserData"].id;
    },
    targetable: function () {
      return this.validTarget;
    },
  },
};
</script>